const bissell = {
	vacuums: [
		{
			id: 1000,
			imageLocation: '/images/vacuums/BGU1451T.jpg',
			model: 'BGU1451T',
			powerCord: '30 feet',
			weight: '12 lbs',
			vacuumWidth: '13 inches',
			features: ['carry handle', '5 positions adjustment', '10 amp'],
			extras: [
				'crevice tool',
				'dusting brush',
				'upholstery tool',
				'extension wand',
			],
		},
		{
			id: 1001,
			imageLocation: '/images/vacuums/BGU1937T.jpg',
			model: 'BGU1937T',
			powerCord: '30 feet',
			weight: '11.25 lbs',
			vacuumWidth: '13.5 inches',
			features: ['carry handle', '5 positions adjustment', '8 amp'],
			extras: [
				'crevice tool',
				'dusting brush',
				'upholstery tool',
				'extension wand',
			],
		},
		{
			id: 1002,
			imageLocation: '/images/vacuums/BGU8000.jpg',
			model: 'BGU8000',
			powerCord: '40 feet',
			weight: '8 lbs',
			vacuumWidth: '13 inches',
			features: [
				'carry handle',
				'self adjusting positions adjustment',
				'4 amp',
			],
			extras: [
				'cord guard',
				'soft wheels protect wood floors',
				'large rear wheels',
			],
		},
		{
			id: 1003,
			imageLocation: '/images/vacuums/BGU8500.jpg',
			model: 'BGU8500',
			powerCord: '40 feet',
			weight: '8 lbs',
			vacuumWidth: '13 inches',
			features: [
				'carry handle',
				'self adjusting positions adjustment',
				'4 amp',
			],
			extras: [
				'cord guard',
				'soft wheels protect wood floors',
				'large rear wheels',
			],
		},
		{
			id: 1004,
			imageLocation: '/images/vacuums/BG100.jpg',
			model: 'BG100',
			powerCord: '50 feet',
			weight: '13.5 lbs',
			vacuumWidth: '12 inches',
			features: [
				'6 positions adjustment',
				'metal foot switch',
				'870 watt motor',
			],
			extras: [
				'large rear wheels',
				'reinforced fan',
				'see-thru fan chamber for fast cleaning',
			],
		},
		{
			id: 1005,
			imageLocation: '/images/vacuums/BG101.jpg',
			model: 'BG101',
			powerCord: '50 feet',
			weight: '14.5 lbs',
			vacuumWidth: '12 inches',
			features: [
				'6 positions adjustment',
				'metal foot switch',
				'870 watt motor',
			],
			extras: [
				'large rear wheels',
				'reinforced fan',
				'see-thru fan chamber for fast cleaning',
				'magnet bar',
			],
		},
		{
			id: 1006,
			imageLocation: '/images/vacuums/BG101H.jpg',
			model: 'BG101H',
			powerCord: '50 feet',
			weight: '14.5 lbs',
			vacuumWidth: '12 inches',
			features: [
				'6 positions adjustment',
				'metal foot switch',
				'5.5 amp',
				'heat overload protection system',
			],
			extras: [
				'large rear wheels',
				'reinforced fan',
				'see-thru fan chamber for fast cleaning',
				'magnet bar',
			],
		},
		{
			id: 1007,
			imageLocation: '/images/vacuums/BG107HQS.jpg',
			model: 'BG107HQS',
			powerCord: '50 feet',
			weight: '14.5 lbs',
			vacuumWidth: '12 inches',
			features: [
				'sound pressure 68 dBA',
				'6 positions adjustment',
				'metal foot switch',
				'5.5 amp',
				'heat overload protection system',
			],
			extras: [
				'large rear wheels',
				'reinforced fan',
				'see-thru fan chamber for fast cleaning',
				'magnet bar',
			],
		},
		{
			id: 1008,
			imageLocation: '/images/vacuums/BG101DC.jpg',
			model: 'BG101DC',
			powerCord: '50 feet',
			weight: '14.5 lbs',
			vacuumWidth: '12 inches',
			features: [
				'6 positions adjustment',
				'metal foot switch',
				'870 watt motor',
				'heat overload protection system',
			],
			extras: [
				'large rear wheels',
				'reinforced fan',
				'see-thru fan chamber for fast cleaning',
				'magnet bar',
			],
		},
		{
			id: 1009,
			imageLocation: '/images/vacuums/BG102.jpg',
			model: 'BG102',
			powerCord: '50 feet',
			weight: '16.5 lbs',
			vacuumWidth: '16 inches',
			features: [
				'metal foot switch',
				'870 watt motor',
				'heat overload protection system',
				'6 positions adjustment',
			],
			extras: [
				'large rear wheels',
				'reinforced fan',
				'see-thru fan chamber for fast cleaning',
				'magnet bar',
			],
		},
		{
			id: 1010,
			imageLocation: '/images/vacuums/BG102H.jpg',
			model: 'BG102H',
			powerCord: '50 feet',
			weight: '17 lbs',
			vacuumWidth: '16 inches',
			features: [
				'metal foot switch',
				'870 watt motor',
				'heat overload protection system',
				'6 positions adjustment',
			],
			extras: [
				'large rear wheels',
				'reinforced fan',
				'see-thru fan chamber for fast cleaning',
				'magnet bar',
			],
		},
		{
			id: 1011,
			imageLocation: '/images/vacuums/BG10716HQS.jpg',
			model: 'BG107/16HQS',
			powerCord: '50 feet',
			weight: '14.5 lbs',
			vacuumWidth: '16 inches',
			features: [
				'sound pressure 68 dBA',

				'metal foot switch',
				'5.5 amp motor',
				'heat overload protection system',
				'6 positions adjustment',
			],
			extras: [
				'large rear wheels',
				'reinforced fan',
				'see-thru fan chamber for fast cleaning',
				'magnet bar',
			],
		},
		{
			id: 1011,
			imageLocation: '/images/vacuums/BG10716HQS.jpg',
			model: 'BG107/16HQS',
			powerCord: '50 feet',
			weight: '14.5 lbs',
			vacuumWidth: '16 inches',
			features: [
				'sound pressure 68 dBA',

				'metal foot switch',
				'5.5 amp motor',
				'heat overload protection system',
				'6 positions adjustment',
			],
			extras: [
				'large rear wheels',
				'reinforced fan',
				'see-thru fan chamber for fast cleaning',
				'magnet bar',
			],
		},
		{
			id: 1012,
			imageLocation: '/images/vacuums/BG102DC.jpg',
			model: 'BG102DC',
			powerCord: '50 feet',
			weight: '17.5 lbs',
			vacuumWidth: '16 inches',
			features: [
				'dirt cup design',

				'metal foot switch',
				'870 watt motor',
				'heat overload protection system',
				'6 positions adjustment',
			],
			extras: [
				'large rear wheels',
				'reinforced fan',
				'see-thru fan chamber for fast cleaning',
				'magnet bar',
			],
		},
		{
			id: 1013,
			imageLocation: '/images/vacuums/BG1000.jpg',
			model: 'BG1000',
			powerCord: '50 feet',
			weight: '19 lbs',
			vacuumWidth: '15 inches',
			features: [
				'heavy-duty commercial vacuum',
				'sound pressure 67 dBA',
				'two-motor system',
				'120V, 1080W, 9A',
			],
			extras: ['full handle detent', 'crevice tool', '2 in 1 upholstery tool'],
		},
		{
			id: 1014,
			imageLocation: '/images/vacuums/BGPRO12T.jpg',
			model: 'BGPRO12T',
			powerCord: '48 feet',
			weight: '17 lbs',
			vacuumWidth: '12 inches',
			features: [
				'heavy-duty commercial vacuum',
				'sound pressure 68 dBA',
				'1,000 watt motor',
				'Auto motor shutoff when machine is clogged',
			],
			extras: ['crevice tool', 'upholstery tool', 'dusting brush'],
		},
		{
			id: 1015,
			imageLocation: '/images/vacuums/BGPRO14T.jpg',
			model: 'BGPRO14T',
			powerCord: '46 feet',
			weight: '19 lbs',
			vacuumWidth: '14 inches',
			features: [
				'heavy-duty commercial vacuum',
				'sound pressure 67 dBA',
				'1,000 watt motor',
				'Auto motor shutoff when machine is clogged',
				'14″ or 18″ cleaning path for faster cleaning',
				'manuel carpet height adjustment',
				'Electronic sensors detect a broken belt or blocked air flow',
			],
			extras: [
				'large rear wheels',
				'crevice tool',
				'upholstery tool',
				'dusting brush',
				'Telescopic wand',
			],
		},
		{
			id: 1016,
			imageLocation: '/images/vacuums/BGPRO18T.jpg',
			model: 'BGPRO18T',
			powerCord: '46 feet',
			weight: '20 lbs',
			vacuumWidth: '18 inches',
			features: [
				'heavy-duty commercial vacuum',
				'sound pressure 67 dBA',
				'1,000 watt motor',
				'Auto motor shutoff when machine is clogged',
				'14″ or 18″ cleaning path for faster cleaning',
				'manuel carpet height adjustment',
				'Electronic sensors detect a broken belt or blocked air flow',
			],
			extras: [
				'large rear wheels',
				'crevice tool',
				'upholstery tool',
				'dusting brush',
				'Telescopic wand',
			],
		},

		{
			id: 1017,
			imageLocation: '/images/vacuums/BGC3000.jpg',
			model: 'BGC3000',
			powerCord: '30 feet',
			weight: '10.6 lbs',

			features: [
				'sound pressure 62 dBA',
				'9 amps',
				'ultra quiet low noise technology',
				'uses 20% less energy with 30% more power',
				'Ametek Advantek powered motor',
			],
			extras: [
				'8-piece tool kit – combo rug & floor tool with swivel neck & rear wheels, upholstery tool w/slide-on brush, round brush, floor tool, crevice tool & metal telescopic wand',
			],
		},
		{
			id: 1018,
			imageLocation: '/images/vacuums/BGCOMP9H.jpg',
			model: 'BGCOMP9H',
			powerCord: '50 feet',
			weight: '10.6 lbs',

			features: [
				'sound pressure 60 dBA',
				'1,200 watts motor',
				'quiet and lightweight',
				'versatile machine – cleans carpet, upholstery and more',
			],
			extras: [
				'On-board cleaning tools included: crevice tool, upholstery tool, dusting brush, combination floor tool, metal telescoping wand',
				'',
			],
		},
		{
			id: 1019,
			imageLocation: '/images/vacuums/BGC2000.jpg',
			model: 'BGC2000',
			powerCord: '15 feet',
			weight: '10.6 lbs',

			features: [
				'sound pressure 84 dBA',
				'1,000 watts motor',
				'quiet and lightweight',
				'compact design',
				'ultra-portable and super-powerful',
				'carry handle',
			],
			extras: [
				'2-in-1 floor tool and two extension wands for those hard to reach places',
				'Permanent wheels for easy maneuverability',
			],
		},

		{
			id: 1020,
			imageLocation: '/images/vacuums/BG1006.jpg',
			model: 'BG1006',
			powerCord: '50 feet',
			weight: '9.5 lbs',

			features: [
				'patent pending adjustable shoulder strap & waist belt design so the machine rests off your back',
				'ametek motor with built in heat sensor',
				'1,175 watt motor',
				'Twist off lid',
				'1 1/2″ crushproof 4′ vacuum hose with swivel cuffs',
				'On/Off switch with power nozzle hook up for easy finger tip control',
			],
			extras: [],
		},
		{
			id: 1021,
			imageLocation: '/images/vacuums/BG1001.jpg',
			model: 'BG1001',
			powerCord: '50 feet',
			weight: '10.5 lbs',

			features: [
				'patent pending adjustable shoulder strap & waist belt design so the machine rests off your back',
				'1,175 watt motor',
				'ametek motor with built in heat sensor',
				'Twist off lid',
				'1 1/2″ crushproof 4′ vacuum hose with swivel cuffs',
				'On/Off switch with power nozzle hook up for easy finger tip control',
			],
			extras: ['8 Piece Tool Kit'],
		},
		{
			id: 1022,
			imageLocation: '/images/vacuums/BGHIP6A.jpg',
			model: 'BGHIP6A',
			powerCord: '50 feet',
			weight: '7.5 lbs',

			features: [
				'patent pending adjustable shoulder strap & waist belt design so the machine rests off your back',
				'1,200 watt motor',
				'ametek motor',
				'6 quart capacity',
				'impact proof polyethylene body',
				'sound pressure 69 dBA',
				'On/Off switch with power nozzle hook up for easy finger tip control',
			],
			extras: ['Optional 15″ Power head'],
		},
		{
			id: 1023,
			imageLocation: '/images/vacuums/BGBPAK1.jpg',
			model: 'BGBPAK1',
			features: [
				'Commercial geared 15 inch power nozzle with upper Sheath assembly and lower wand',
				'1 1/2″ – 1 1/4″ reducer handle that fits on hose cuff',
				'Power cord assembly connects to switch box on backpack',
				'Built-In storage ring for convenient wall mounting',
				'Double row of bristles for rug and floor cleaning',
			],
			extras: [],
		},
		{
			id: 1024,
			imageLocation: '/images/vacuums/BGBP06H.jpg',
			model: 'BGBP06H',
			powerCord: '50 feet',
			weight: '9.8 lbs',

			features: [
				'1,328 watt motor',
				'6 quart capacity',
				'Non-clogging hose with particulate deflector',
				'Cool-air channels eliminate heat transferring to your back',
				'Waffle noise suppression for whisper-quiet operation',
				'Cord retainer',
				'Padded ergonomic backrest',
			],
			extras: [],
		},
		{
			id: 1025,
			imageLocation: '/images/vacuums/BGBP10H.jpg',
			model: 'BGBP10H',
			powerCord: '50 feet',
			weight: '10.8 lbs',

			features: [
				'1,328 watt motor',
				'10 quart capacity',
				'Non-clogging hose with particulate deflector',
				'Cool-air channels eliminate heat transferring to your back',
				'Waffle noise suppression for whisper-quiet operation',
				'Cord retainer',
				'Padded ergonomic backrest',
			],
			extras: [],
		},
		{
			id: 1026,
			imageLocation: '/images/vacuums/BG-CC28.jpg',
			model: 'BG-CC28',
			powerCord: '60 feet',
			weight: '57 lbs',
			vacuumWidth: '29 inches',
			features: [
				'8.5 amp motor',
				'sound pressure 78 dBA',
				'Air velocity enhancer edge cleaning',
				'Floating brush barrier',
				'5 position height adjustment',
				'rugged 360° front swivel wheels for short turning radius',
				'Fold-down-handle',
				'Multiple sizes 24″ & 28″',
			],
			extras: [],
		},
	],
};
